# 单阶段：弱口令扫描 → 弱口令扫描结果.xml
exportTemplateId: tpl-svmp-phase-weakpwd
displayName: 弱口令扫描
match:
  capability: weakPasswordScan
output:
  format: SVMP-XML
  encoding: UTF-8
  fileName: 弱口令扫描结果.xml
  rootElement: WeakPasswordScanResult
trigger:
  on: TASK_COMPLETED
fields:
  - target: assetKey
    source: assetKey  # 扫描目标对应资产 库资产 IP
  - target: assetName
    source: assetName  # 对应的 TVM 资产管 理中的资产 名称
  - target: asset_pwds
    source: asset_pwds  # 弱口令信息 {
  - target: baseInfo
    source: baseInfo  # 任务基础信息
  - target: count
    source: count  # 猜测次数
  - target: device
    source: device  # 任务设备信息 {
  - target: execType
    source: execType  # 执行方式
  - target: hostCount
    source: hostCount  # 任务存活目标 数
  - target: id
    source: id  # 任务策略 ID
  - target: interval
    source: interval  # 口令猜测频率 （秒）
  - target: ipType
    source: ipType  # IP 类型（ IPv4/IPv6 /URL ）
  - target: isSystem
    source: isSystem  # 是否系统弱口令 }],
  - target: os
    source: os  # 操作系统
  - target: other_info
    source: other_info
  - target: password
    source: password  # 弱口令密码
  - target: product
    source: product  # 任务涉及设备 型号
  - target: pswdGuess
    source: pswdGuess  # 口令猜测配置
  - target: scanInfo
    source: scanInfo
  - target: scanTimes
    source: scanTimes  # 扫描次数
  - target: source
    source: source  # 数据来源
  - target: status
    source: status  # 当前风险同步状态
  - target: summary
    source: summary  # 综述信息
  - target: target
    source: target  # 扫描目标信息
  - target: taskCount
    source: taskCount  # 策略已执行任 务数量
  - target: taskSource
    source: taskSource
  - target: taskStatus
    source: taskStatus
  - target: taskType
    source: taskType  # 任务类型
  - target: taskUuid
    source: taskUuid  # 扫描目标所在子任 务 UUID
  - target: thread
    source: thread  # 最大并发线程 数
  - target: timeout
    source: timeout  # 口令猜测时间 （分钟）
  - target: userName
    source: userName  # 弱口令用户名
  - target: weakAccountInfo
    source: weakAccountInfo  # 弱口令信息 {
