# 系统漏洞扫描 → 系统漏洞扫描结果.xml
exportTemplateId: tpl-svmp-phase-vuln
displayName: 系统漏洞扫描
match:
  capability: vulnScan
  engineXmlFormat: aurora
  officialSample: 系统漏洞扫描结果.xml
output:
  format: SVMP-XML
  encoding: UTF-8
  fileName: 系统漏洞扫描结果.xml
  rootElement: aurora
  # 绿盟 Aurora：aurora/data/report/targets/...
trigger:
  on: TASK_COMPLETED
fields:
  - target: hostCount
    source: hostCount  # aurora/report/scanned_ip_count
  - target: riskValue
    source: riskValue  # aurora/report/targets/target/host_score
  - target: assetKey
    source: assetKey  # aurora/report/targets/target/ip
  - target: riskValue
    source: riskValue  # aurora/report/targets/target/vul_score
  - target: cnvd
    source: cnvd  # aurora/report/targets/target/vuln_detail/vuln/cncve
  - target: cnvd
    source: cnvd  # aurora/report/targets/target/vuln_detail/vuln/cnnvd
  - target: cve
    source: cve  # aurora/report/targets/target/vuln_detail/vuln/cve_id
  - target: syncTime
    source: syncTime  # aurora/report/targets/target/vuln_detail/vuln/date_found
  - target: others
    source: others  # aurora/report/targets/target/vuln_detail/vuln/description
  - target: name
    source: name  # aurora/report/targets/target/vuln_detail/vuln/name
  - target: vulLocalId
    source: vulLocalId  # aurora/report/targets/target/vuln_detail/vuln/plugin_id
  - target: cvss
    source: cvss  # aurora/report/targets/target/vuln_detail/vuln/risk_points
  - target: others
    source: others  # aurora/report/targets/target/vuln_detail/vuln/solution
  - target: others
    source: others  # aurora/report/targets/target/vuln_detail/vuln/threat_category
  - target: vulLocalId
    source: vulLocalId  # aurora/report/targets/target/vuln_detail/vuln/vul_id
  - target: others
    source: others  # aurora/report/targets/target/vuln_scanned/vuln/mess_string
  - target: port
    source: port  # aurora/report/targets/target/vuln_scanned/vuln/port
  - target: protocol
    source: protocol  # aurora/report/targets/target/vuln_scanned/vuln/protocol
  - target: service
    source: service  # aurora/report/targets/target/vuln_scanned/vuln/service
  - target: status
    source: status  # aurora/report/targets/target/vuln_scanned/vuln/vul_confirmed
  - target: vulLocalId
    source: vulLocalId  # aurora/report/targets/target/vuln_scanned/vuln/vul_id
  - target: id
    source: id  # aurora/report/task/id
  - target: baseInfo
    source: baseInfo  # aurora/report/task/name
  - target: taskType
    source: taskType  # aurora/report/task/task_type
  - target: syncTime
    source: syncTime  # aurora/report/task/time_end_scan
  - target: scanTimes
    source: scanTimes  # aurora/report/task/time_start_scan
