# 弱口令扫描 → 弱口令扫描结果.xml
exportTemplateId: tpl-svmp-phase-weakpwd
displayName: 弱口令扫描
match:
  capability: weakPasswordScan
  engineXmlFormat: aurora
  officialSample: 弱口令扫描结果.xml
output:
  format: SVMP-XML
  encoding: UTF-8
  fileName: 弱口令扫描结果.xml
  rootElement: aurora
  # 绿盟 Aurora：aurora/data/report/targets/...
trigger:
  on: TASK_COMPLETED
fields:
  - target: assetKey
    source: assetKey  # aurora/report/targets/target/ip
  - target: password
    source: password  # aurora/report/targets/target/password_results/password_result/password
  - target: service
    source: service  # aurora/report/targets/target/password_results/password_result/type
  - target: userName
    source: userName  # aurora/report/targets/target/password_results/password_result/username
  - target: name
    source: name  # aurora/report/targets/target/vuln_detail/vuln/name
  - target: weakAccountInfo
    source: weakAccountInfo  # aurora/report/targets/target/vuln_scanned/vuln/mess_string
  - target: port
    source: port  # aurora/report/targets/target/vuln_scanned/vuln/port
  - target: vulLocalId
    source: vulLocalId  # aurora/report/targets/target/vuln_scanned/vuln/vul_id
  - target: id
    source: id  # aurora/report/task/id
  - target: taskType
    source: taskType  # aurora/report/task/task_type
