# 由《数据外发字段说明》章节「主机扫描」生成，请校对 source 映射
exportTemplateId: tpl-svmp-task-type-1
displayName: 主机扫描
match:
  engineTaskType: 1  # TASK_SYS_SCAN
  scanTemplateIds: []  # 可选：再细绑 scanTemplateId
output:
  format: SVMP-TAR-GZ
  packageFiles:
    - task_info.txt
    - asset_info.txt
    - asset_vuls.txt
    - vul_info.txt
  encoding: UTF-8
trigger:
  on: TASK_COMPLETED
filter:
  vulInfoStatList: [1, 2, 3, 5, 6, 7, 8, 9, 10]
fields:
  - target: baseInfo
    source: baseInfo  # 任务基础信息
  - target: device
    source: device  # 任务设备信息 {
  - target: ipType
    source: ipType  # IP 类型（ IPv4/IPv6 /URL ）
  - target: source
    source: source  # 数据来源
  - target: sysScan
    source: sysScan  # 系统配置
  - target: debug
    source: debug  # 调试模式
  - target: oracle
    source: oracle  # 是否启用 Ora cle 漏洞深度扫描
  - target: portScan
    source: portScan  # 端口配置
  - target: udp
    source: udp  # UDP 扫描
  - target: speed
    source: speed  # 扫描速度
  - target: liveCheck
    source: liveCheck  # 存活探测配置
  - target: tcp
    source: tcp  # 是否开启 TCP PING
  - target: icmp
    source: icmp  # 是否开启 ICM P PING
  - target: live
    source: live  # 是否开启主机 存活测试
  - target: ports
    source: ports  # TCP PING 端口范围
  - target: taskCount
    source: taskCount  # 策略已执行任 务数量
  - target: scanTimes
    source: scanTimes  # 扫描次数
  - target: execType
    source: execType  # 执行方式
  - target: id
    source: id  # 任务策略 ID
  - target: taskType
    source: taskType  # 任务类型
  - target: hostCount
    source: hostCount  # 任务存活目标 数
  - target: product
    source: product  # 任务涉及设备 型号
  - target: target
    source: target  # 扫描目标信息
  - target: summary
    source: summary  # 综述信息
  - target: assetKey
    source: assetKey  # 扫描目标对应资产 库资产 IP
  - target: assetName
    source: assetName  # 对应的 TVM 资产管 理中的资产 名称
  - target: status
    source: status  # 当前风险同步状态
  - target: taskUuid
    source: taskUuid  # 扫描目标所在子任 务 UUID
  - target: os
    source: os  # 操作系统
  - target: riskValue
    source: riskValue  # 风险值
  - target: riskLevel
    source: riskLevel  # 风险等级
  - target: syncTime
    source: syncTime  # 风险同步时间
  - target: others
    source: others  # 漏洞描述
  - target: cnvd
    source: cnvd  # 漏洞 cn vd
  - target: cve
    source: cve  # 漏洞 cve
  - target: cvss
    source: cvss  # 漏洞 CVSS
  - target: vulLocalId
    source: vulLocalId  # 漏洞 名称
  - target: name
    source: name  # 漏洞 名称
  - target: times
    source: times  # 漏洞出现次数 } 4.asset_ vuls.txt 任务扫描目标与漏洞关联信息 也就是 处置单 / 系统漏洞信息 文件内容及含义 {
