# 端口扫描 → 端口扫描结果.xml
exportTemplateId: tpl-svmp-phase-port
displayName: 端口扫描
match:
  capability: portScan
output:
  format: SVMP-XML
  encoding: UTF-8
  fileName: 端口扫描结果.xml
  rootElement: PortScanResult
trigger:
  on: TASK_COMPLETED
fields:
  - target: assetKey
    source: assetKey
  - target: assetName
    source: assetName
  - target: baseInfo
    source: baseInfo
  - target: device
    source: device
  - target: execType
    source: execType
  - target: geo
    source: geo
  - target: geo_id
    source: geo_id
  - target: hostCount
    source: hostCount
  - target: id
    source: id
  - target: ip
    source: ip
  - target: ipType
    source: ipType
  - target: mac
    source: mac
  - target: os
    source: os
  - target: osName
    source: osName
  - target: port
    source: port
  - target: portScan
    source: portScan
  - target: product
    source: product
  - target: scanInfo
    source: scanInfo
  - target: scanTimes
    source: scanTimes
  - target: software
    source: software
  - target: source
    source: source
  - target: speed
    source: speed
  - target: status
    source: status
  - target: summary
    source: summary
  - target: target
    source: target
  - target: taskCount
    source: taskCount
  - target: taskSource
    source: taskSource
  - target: taskStatus
    source: taskStatus
  - target: taskType
    source: taskType
  - target: taskUuid
    source: taskUuid
  - target: type
    source: type
  - target: udp
    source: udp
