# -*- coding: utf-8 -*-
# ASCII-only: CJK encoded as \uXXXX string literals
from pathlib import Path

P = []
def a(*x):
    for v in x: P.append(v)

CSS = (
    ":root{--p:#1890ff;--s:#52c41a;--w:#faad14;--e:#ff4d4f;--t:rgba(0,0,0,.85);--ts:rgba(0,0,0,.45);--b:#d9d9d9;--bg:#f0f2f5;--c:#fff;--sb:#001529}"
    "*{box-sizing:border-box;margin:0;padding:0}"
    "body{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"PingFang SC\",\"Microsoft YaHei\",sans-serif;font-size:14px;color:var(--t);background:var(--bg);line-height:1.6}"
    ".app{display:flex;min-height:100vh}"
    ".side{width:256px;background:var(--sb);color:#fff;flex-shrink:0;position:sticky;top:0;height:100vh;overflow-y:auto;scrollbar-width:none}"
    ".logo{padding:16px 20px;font-size:15px;font-weight:700;border-bottom:1px solid rgba(255,255,255,.1);line-height:1.4}"
    ".logo small{display:block;font-size:11px;font-weight:400;opacity:.55;margin-top:2px}"
    ".ng{padding:16px 0 4px}.nt{padding:3px 20px;font-size:10px;color:rgba(255,255,255,.3);letter-spacing:.5px;text-transform:uppercase}"
    ".ni{display:block;padding:7px 20px 7px 32px;color:rgba(255,255,255,.6);font-size:13px;cursor:pointer;text-decoration:none;border-left:3px solid transparent}"
    ".ni:hover{color:#fff;background:rgba(255,255,255,.06)}"
    ".ni.active{color:#fff;background:rgba(24,144,255,.15);border-left-color:var(--p)}"
    ".main{flex:1;overflow:auto;min-width:0}"
    ".topbar{height:52px;background:var(--c);border-bottom:1px solid #f0f0f0;display:flex;align-items:center;padding:0 28px;position:sticky;top:0;z-index:99;gap:12px;box-shadow:0 1px 4px rgba(0,0,0,.06)}"
    ".topbar-t{font-weight:600;font-size:15px}"
    ".ct{padding:28px;max-width:1140px}"
    ".sec{display:none}.sec.active{display:block}"
    ".card{background:var(--c);border-radius:6px;box-shadow:0 1px 3px rgba(0,0,0,.06);margin-bottom:24px;border:1px solid #f0f0f0}"
    ".ch{padding:16px 24px;border-bottom:1px solid #f0f0f0;font-weight:600;font-size:14px;display:flex;align-items:center;gap:10px}"
    ".cb{padding:20px 24px}"
    "table{width:100%;border-collapse:collapse}"
    "th,td{padding:10px 14px;border-bottom:1px solid #f0f0f0;vertical-align:top;font-size:13px}"
    "th{background:#fafafa;font-weight:600;white-space:nowrap;color:var(--ts)}"
    "td code,th code{font-size:11px;background:#f5f5f5;padding:1px 6px;border-radius:3px;font-family:Consolas,monospace;color:#c7254e}"
    ".bdg{display:inline-block;padding:1px 8px;border-radius:10px;font-size:11px;font-weight:600;border:1px solid;line-height:1.8}"
    ".b0{background:#e6f7ff;border-color:#91d5ff;color:#0958d9}"
    ".b1{background:#f6ffed;border-color:#b7eb8f;color:#389e0d}"
    ".b2{background:#fff7e6;border-color:#ffd591;color:#d46b08}"
    ".b3{background:#f9f0ff;border-color:#d3adf7;color:#531dab}"
    ".b4{background:#fff2f0;border-color:#ffccc7;color:#cf1322}"
    ".b5{background:#fafafa;border-color:#d9d9d9;color:#595959}"
    ".b6{background:#fff0f6;border-color:#ffadd2;color:#c41d7f}"
    ".al{padding:12px 18px;border-radius:6px;margin-bottom:18px;font-size:13px;line-height:1.7;border-left:4px solid}"
    ".ai{background:#e6f7ff;border-color:var(--p);color:#0050b3}"
    ".aw{background:#fffbe6;border-color:var(--w);color:#874d00}"
    ".ae{background:#fff2f0;border-color:var(--e);color:#a8071a}"
    ".as{background:#f6ffed;border-color:var(--s);color:#135200}"
    ".code{background:#1e1e2e;color:#cdd6f4;border-radius:6px;padding:18px 22px;font-family:Consolas,\"Courier New\",monospace;font-size:12px;line-height:1.9;white-space:pre;overflow-x:auto;margin-bottom:0}"
    ".grid2{display:grid;grid-template-columns:1fr 1fr;gap:18px}"
    ".grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}"
    ".grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}"
    ".kpi{background:var(--c);border:1px solid #f0f0f0;border-radius:6px;padding:18px;}"
    ".kpi .n{font-size:30px;font-weight:700;margin-bottom:4px;line-height:1}"
    ".kpi .l{font-size:12px;color:var(--ts)}"
    ".tl{border-left:3px solid #e8e8e8;padding-left:22px;margin-left:10px}"
    ".tli{margin-bottom:18px;position:relative}"
    ".tli::before{content:\"\";width:12px;height:12px;border-radius:50%;background:var(--p);position:absolute;left:-29px;top:3px;border:2px solid var(--bg);box-shadow:0 0 0 2px var(--p)}"
    ".tli.done::before{background:var(--s);box-shadow:0 0 0 2px var(--s)}"
    ".tli.pend::before{background:#d9d9d9;box-shadow:0 0 0 2px #d9d9d9}"
    ".tl-h{font-weight:600;margin-bottom:4px;font-size:13px}"
    ".tl-d{color:var(--ts);font-size:12px;line-height:1.7}"
    ".steps{display:flex;align-items:center;flex-wrap:wrap;gap:4px;margin:12px 0}"
    ".step{padding:8px 14px;background:#e6f7ff;border:1px solid #91d5ff;border-radius:6px;font-size:12px;text-align:center;line-height:1.4}"
    ".sarr{padding:0 4px;color:#91d5ff;font-size:16px}"
    ".fc{background:#1e1e2e;border-radius:6px;padding:18px 22px;font-family:Consolas,monospace;font-size:12px;color:#cdd6f4;line-height:1.9;white-space:pre;overflow-x:auto}"
    ".sm{background:#fafafa;border:1px solid #e8e8e8;border-radius:4px;padding:14px;font-family:Consolas,monospace;font-size:12px;line-height:1.8;white-space:pre}"
    ".ht{color:var(--e);font-weight:600}.hm{color:var(--w)}.hl{color:var(--s)}"
    "h3{font-size:14px;font-weight:600;margin:20px 0 10px;padding-top:4px;border-top:1px solid #f0f0f0}"
    "h3:first-child{border-top:none;margin-top:0}"
    ".sep{height:1px;background:#f0f0f0;margin:20px 0}"
)

